### PR TITLE
feat: static client

### PR DESCRIPTION
**Pull request by somehowchris**
Now heres a thing, I do not know if this should be done, I couldn't find any panics or errors so far and it brings the crates time to handle a request from `4ms` to `120ns`

### CODE REVIEW

**Comment by somehowchris** [comment]
#10

**Comment by somehowchris** [comment]
Now @felipenoris I have come across a thought and since it's your crate I wanna hear your opinion.

Giving devs the oportunity to configure things is great. How how far should it go? Either you let the user configure a lot via flags, (I might think of things like proxies, etc. in the future) or let the user pass in a hyper client which would be used. This opens up the issue of functional vs OO approaches and the use of multi threaded runtimes

**Comment by felipenoris** [comment]
@somehowchris , the way I see it, I think it is for the better to let the user pass the client and avoid the complexity of handling different scenarios with flags. When there are only 2 ou 3 three options, flags are Ok, but more than that I think software composability is the way.
The issue here is that the user should pass a client builder, maybe something implementing a trait, right? The package could then define a basic HttpClientBuilder implementing that trait and let the user provide different implementations. The https example could be in the docs.

**Comment by somehowchris** [comment]
A client builder? So propose this crate still ads some specific things to the client builder?

**Comment by felipenoris** [comment]
@somehowchris not exactly.
As far as I could understand, the package needs to create a new client for each proxied request.
The user has to have a way to provide a function to the package that lets the package create new clients as needed. Maybe the implementation of that funcion from the user just creates a new connection (as what this package did originally), or maybe it takes a connection from a pool and everything. One way to do it is to let the user implement a trait. I'm not talking about the `Client::builder()`.

**Comment by felipenoris** [comment]
@somehowchris nice! Would you update the docs on this?
Btw, please consider adding your name to the `authors` tag in the `Cargo.toml` file if you like.

**Comment by somehowchris** [comment]
@felipenoris Its been an idea, currently trying to rewrite the tests 😅  sry, will mark it as draft

**Comment by somehowchris** [comment]
Basically took the approach of the `lazystatic` thing for the client out of the crate, into the example. Also edited the security part to be a small guide on what to think about

**Pull request merged**
