### PR TITLE
feat: use criterion for benching

### PR DESCRIPTION
**Pull request by somehowchris**
The rust integrated benching feature (which is also unstable) uses a naive approch.

I have come to learn criterion better. It is not a perfect solution and ci result aren't all the time trustworthy but are a good indication.

This also adds a `bench` feature which allows the benching parts to access internal functions

### CODE REVIEW

**Comment by somehowchris** [comment]
https://github.com/boa-dev/criterion-compare-action/issues/51

**Comment by somehowchris** [comment]
@felipenoris I'm having final exams, so if one answers or fixes https://github.com/boa-dev/criterion-compare-action/issues/51 I will be able to change or check something in 3-4 weeks sry for that 🦄 

Would be lovely to see all the changes in action :)

**Comment by felipenoris** [comment]
@somehowchris no worries! Good luck!

**Comment by somehowchris** [comment]
I removed the PR gh action for criterion as they do not seem to care about their gh action and using gh actions for benching is kinda risky as its infra is on a public could which means your results will be load depending and for something like valgrind we do not know how the l1,l2 & l3 cache behaves for ghs infra

**Comment by somehowchris** [comment]
This should solve #37 and #31

**Pull request merged**
